---
# Debug...
# - template:
#     src: templates/network.xml.j2
#     dest: network.xml     

- name: Create tftp directory
  file:
    path: "{{ bootp_tftp_dir }}"
    state: directory
    mode: '0755'
    
- name: Define network {{ cluster_name }}
  virt_net:
    command: define
    name: "{{ cluster_name }}"
    xml: "{{ lookup('template', 'templates/network.xml.j2') }}"

- name: Active network {{ cluster_name }}
  virt_net:
    state: active
    name: "{{ cluster_name }}"

- name: Activate autostart network {{ cluster_name }}
  virt_net:
    autostart: yes
    name: "{{ cluster_name }}"

- name: Add network to internal network zone
  firewalld:
    source: "{{ vn_subnet }}/24"
    zone: internal
    state: enabled
    permanent: yes
  notify: 'reload firewalld'
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '7'

- name: firewalld reload
  command: firewall-cmd --reload
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '7'
