---
# defaults file for ocp4-ai-prepare-libvirt

bootp_tftp_dir: /var/lib/tftpboot

vn_subnet: "192.168.50.0"
vn_name: "openshift-4-cluster"
vn_internal_domain: "compute.local"
vn_public_domain: "h42.openshift.pub"

listen_address: "{{ hostvars['localhost']['ansible_default_ipv4']['address'] }}"

master_count: 3
master_vcpu: 4
master_memory_size: 16384
master_memory_unit: 'MiB'
# qemu-img image size specified.
#   You may use k, M, G, T, P or E suffixe
master_root_disk_size: '120G'

compute_count: 2

vm_autostart: false
